=== alexbalak21/Report-Generator/mappings/rapport_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="rapport_data">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="row" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>

              <xs:element name="date_rapport" type="xs:string" minOccurs="0"/>
              <xs:element name="appellation_produit" type="xs:string" minOccurs="0"/>
              <xs:element name="nom_entreprise_client" type="xs:string" minOccurs="0"/>
              <xs:element name="adresse_entreprise_client" type="xs:string" minOccurs="0"/>
              <xs:element name="nom_destinataire" type="xs:string" minOccurs="0"/>
              <xs:element name="titre_poste_destinataire" type="xs:string" minOccurs="0"/>

              <xs:element name="Lieu_de_prelevment" type="xs:string" minOccurs="0"/>
              <xs:element name="date_heure_prelevment" type="xs:string" minOccurs="0"/>
              <xs:element name="adresse_prelevement" type="xs:string" minOccurs="0"/>
              <xs:element name="ville_prelevement" type="xs:string" minOccurs="0"/>
              <xs:element name="conditions_coservation_reception" type="xs:string" minOccurs="0"/>
              <xs:element name="date_heure_arrive_labo" type="xs:string" minOccurs="0"/>
              <xs:element name="temperature_reception" type="xs:string" minOccurs="0"/>
              <xs:element name="date_heure_mise_en_analyse" type="xs:string" minOccurs="0"/>

              <xs:element name="fournisseur_fabricant" type="xs:string" minOccurs="0"/>
              <xs:element name="nom_produit" type="xs:string" minOccurs="0"/>
              <xs:element name="conditionnement" type="xs:string" minOccurs="0"/>
              <xs:element name="espece" type="xs:string" minOccurs="0"/>
              <xs:element name="agrement" type="xs:string" minOccurs="0"/>
              <xs:element name="origine" type="xs:string" minOccurs="0"/>
              <xs:element name="lot" type="xs:string" minOccurs="0"/>
              <xs:element name="date_emabalage" type="xs:string" minOccurs="0"/>
              <xs:element name="code_article" type="xs:string" minOccurs="0"/>
              <xs:element name="dlc" type="xs:string" minOccurs="0"/>

              <xs:element name="lot_precice" type="xs:string" minOccurs="0"/>
              <xs:element name="imp" type="xs:string" minOccurs="0"/>
              <xs:element name="k_value" type="xs:string" minOccurs="0"/>

              <xs:element name="conformite" type="xs:string" minOccurs="0"/>
              <xs:element name="qualite" type="xs:string" minOccurs="0"/>

              <xs:element name="date_du_jour" type="xs:string" minOccurs="0"/>
              <xs:element name="report_number" type="xs:string" minOccurs="0"/>
              <xs:element name="numero_rapport" type="xs:string" minOccurs="0"/>
              <xs:element name="file_name" type="xs:string" minOccurs="0"/>

            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== alexbalak21/Report-Generator/mappings/rapport_data.xml
<?xml version="1.0" encoding="UTF-8"?>
<rapport_data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="rapport_schema.xsd">

  <row>
    <date_rapport></date_rapport>
    <appellation_produit></appellation_produit>
    <nom_entreprise_client></nom_entreprise_client>
    <adresse_entreprise_client></adresse_entreprise_client>
    <nom_destinataire></nom_destinataire>
    <titre_poste_destinataire></titre_poste_destinataire>

    <Lieu_de_prelevment></Lieu_de_prelevment>
    <date_heure_prelevment></date_heure_prelevment>
    <adresse_prelevement></adresse_prelevement>
    <ville_prelevement></ville_prelevement>
    <conditions_coservation_reception></conditions_coservation_reception>
    <date_heure_arrive_labo></date_heure_arrive_labo>
    <temperature_reception></temperature_reception>
    <date_heure_mise_en_analyse></date_heure_mise_en_analyse>

    <fournisseur_fabricant></fournisseur_fabricant>
    <nom_produit></nom_produit>
    <conditionnement></conditionnement>
    <espece></espece>
    <agrement></agrement>
    <origine></origine>
    <lot></lot>
    <date_emabalage></date_emabalage>
    <code_article></code_article>
    <dlc></dlc>

    <lot_precice></lot_precice>
    <imp></imp>
    <k_value></k_value>

    <conformite></conformite>
    <qualite></qualite>

    <date_du_jour></date_du_jour>
    <report_number></report_number>
    <numero_rapport></numero_rapport>
    <file_name></file_name>
  </row>

</rapport_data>
